### ISSUE TITLE
0.3.0 - Do over

### ISSUE THREAD

**Issue by oscartbeaumont** [specta-rs/rspc#278]
A complete rewrite of rspc to eliminate all cringe.

**Comment by AlexandreCassagne** [comment]
Hey! Do you already have a vision for how this might look?

**Comment by oscartbeaumont** [comment]
Yeah. I'm already working on it on the `main` branch.

The main difference boil down to:
 - tRPC v10-inspired syntax (where the old rspc syntax was tRPC v9 inspired)
 - A complete rearchitecture to support non-JSON formats
 - Spliting functionality out of the core into separate crates to help with versioning

For now i'm focusing on the core Rust stuff and once i'm happy with it I will start reimplement the Axum and Tauri adapters along with bringing back the Typescript.

**Comment by marcusbuffett** [comment]
Are you planning any updates to the request/response layer? Like if I have older clients hanging around (mobile apps), and update the server to 0.3.0, do you expect the older clients can keep requesting with the same format and expecting the same response, or will there be breakage there?

This has been a game-changer to my rust web dev, thank you for this project and specta!

**Comment by oscartbeaumont** [comment]
I am planning to change it but the plan is for all the HTTP format to move outside of the rspc core so it would be entirely possible for a backwards-compatible mode to be implemented.

**Comment by marcusbuffett** [comment]
Sounds good! Excited for the updates
