### ISSUE TITLE
`cargo build --examples` doesn't work

### ISSUE THREAD

**Issue by yonas** [specta-rs/rspc#317]
`cargo build --examples` should build code in the `examples` directory.

**Comment by oscartbeaumont** [comment]
The examples directory is a separate Cargo project as it requires an depedencies I don't want in `Cargo.toml` depedency list. You will need to `cargo run -p example`, `cargo run -p example-axum`, etc.

**Comment by yonas** [comment]
Would adding `[dev-dependencies]` work?

**Comment by oscartbeaumont** [comment]
Yes but:
 - They show up on docs.rs
 - They can be annoying with features (bloating the `Cargo.toml` with dependency overrides for each example and doing that forces publishing examples which i'm not a massive fan of for a crate like this)
 - Would cause a dependency cycle (`rspc` -> `rspc_axum` -> `rspc`) which wouldn't compile.

Another benifit to being a full crate is that a user can copy it out of the rspc repository much easier.
