### ISSUE TITLE
Does not work with vite

### ISSUE THREAD

**Issue by icodeforlove** [specta-rs/rspc#319]
I am unable to use this in vite.

When i do the following on a fresh vite project it fails:

`
import { createReactQueryHooks } from "@rspc/react";
const rspc = createReactQueryHooks();
`

> [vite] Internal server error: Failed to resolve entry for package "@rspc/react". The package may have incorrect main/module/exports specified in its package.json.

**Comment by espeon** [comment]
apparently you're supposed to use [@rspc/react-query](https://www.npmjs.com/package/@rspc/react-query), seems like the docs aren't up to date. i switched and it fixed that issue.

**Comment by icodeforlove** [comment]
@espeon When I switched over to [@rspc/react-query](https://www.npmjs.com/package/@rspc/react-query) it initially failed because it could not find the types.

I was able to manually go into the modules files, and move the type files next to the build files to get that working.

Did this work for you out of the box?

**Comment by espeon** [comment]
No, had to add types as well. Seems to me the dev only somehow exported the built objects and not included the source files/types

**Comment by marcocondrache** [comment]
I've made PR #322 to fix types generation for those packages. @espeon

**Comment by oscartbeaumont** [comment]
Changes have been release. Feel free to reopen the issue if you still have problems!
